---
- name: Optionally run versionscheck if enabled
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Configure /etc/systemd/timesyncd.conf
  ansible.builtin.include_tasks:
    file: 'timesyncd.yml'
  when: ansible_facts['service_mgr'] == "systemd"

- name: Set timezone and install tzdata
  ansible.builtin.include_tasks:
    file: 'timezone.yml'

- name: make sure systemd-timesyncd is started
  ansible.builtin.include_tasks:
    file: 'systemd-timesyncd.yml'
  when: ansible_facts['service_mgr'] == "systemd"
