---
- name: Configure timesyncd.conf
  become: true
  ansible.builtin.template:
    src: 'templates/timesyncd.conf.j2'
    dest: '/etc/systemd/timesyncd.conf'
    mode: '0644'
    owner: 'root'
    group: 'root'
  notify: 'systemctl restart systemd-timesyncd'
