---
timedatectl__timezone: 'Europe/Busingen'

timedatectl__timeservers:
 - ptbtime1.ptb.de
 - ptbtime2.ptb.de
 - ptbtime3.ptb.de
 - 0.pool.ntp.org
 - 1.pool.ntp.org
 - 2.pool.ntp.org
 - 3.pool.ntp.org

timedatectl__rootdistancemaxsec: '5'
timedatectl__pollintervalminsec: '32'
timedatectl__pollintervalmaxsec: '2048'
timedatectl__connectionretrysec: '30'
timedatectl__saveintervalsec: '60'

# version check for this playbook (true is recomended)
submodules_versioncheck: false
