---
timedatectl__timeservers_fallback:
  - '0.debian.pool.ntp.org'
  - '1.debian.pool.ntp.org'
  - '2.debian.pool.ntp.org'
  - '3.debian.pool.ntp.org'
  - '0.arch.pool.ntp.org'
  - '1.arch.pool.ntp.org'
  - '2.arch.pool.ntp.org'
  - '3.arch.pool.ntp.org'

playbook_version_number: 5
ntp__playbook_version_path: 'l3d.time.timedatectl.version'
